/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectOrganizationRouteImport } from './routes/select-organization'
import { Route as RegisterOrganizationRouteImport } from './routes/register-organization'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardOrgslugRouteImport } from './routes/dashboard/$orgslug'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthEmployeeRouteImport } from './routes/auth/employee'
import { Route as DashboardOrgslugIndexRouteImport } from './routes/dashboard/$orgslug/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/auth/forgot-password/index'
import { Route as DashboardOrgslugProductsRouteImport } from './routes/dashboard/$orgslug/products'
import { Route as DashboardOrgslugClientsRouteImport } from './routes/dashboard/$orgslug/clients'
import { Route as AuthForgotPasswordRecoveryRouteImport } from './routes/auth/forgot-password/recovery'
import { Route as DashboardOrgslugTeamsIndexRouteImport } from './routes/dashboard/$orgslug/teams/index'
import { Route as DashboardOrgslugEmployeesIndexRouteImport } from './routes/dashboard/$orgslug/employees/index'
import { Route as DashboardOrgslugTeamsTeamidRouteImport } from './routes/dashboard/$orgslug/teams/$teamid'
import { Route as DashboardOrgslugEmployeesEmployeeidRouteImport } from './routes/dashboard/$orgslug/employees/$employeeid'

const SelectOrganizationRoute = SelectOrganizationRouteImport.update({
  id: '/select-organization',
  path: '/select-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterOrganizationRoute = RegisterOrganizationRouteImport.update({
  id: '/register-organization',
  path: '/register-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrgslugRoute = DashboardOrgslugRouteImport.update({
  id: '/dashboard/$orgslug',
  path: '/dashboard/$orgslug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEmployeeRoute = AuthEmployeeRouteImport.update({
  id: '/auth/employee',
  path: '/auth/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrgslugIndexRoute = DashboardOrgslugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardOrgslugRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/auth/forgot-password/',
  path: '/auth/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrgslugProductsRoute =
  DashboardOrgslugProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => DashboardOrgslugRoute,
  } as any)
const DashboardOrgslugClientsRoute = DashboardOrgslugClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardOrgslugRoute,
} as any)
const AuthForgotPasswordRecoveryRoute =
  AuthForgotPasswordRecoveryRouteImport.update({
    id: '/auth/forgot-password/recovery',
    path: '/auth/forgot-password/recovery',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardOrgslugTeamsIndexRoute =
  DashboardOrgslugTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => DashboardOrgslugRoute,
  } as any)
const DashboardOrgslugEmployeesIndexRoute =
  DashboardOrgslugEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => DashboardOrgslugRoute,
  } as any)
const DashboardOrgslugTeamsTeamidRoute =
  DashboardOrgslugTeamsTeamidRouteImport.update({
    id: '/teams/$teamid',
    path: '/teams/$teamid',
    getParentRoute: () => DashboardOrgslugRoute,
  } as any)
const DashboardOrgslugEmployeesEmployeeidRoute =
  DashboardOrgslugEmployeesEmployeeidRouteImport.update({
    id: '/employees/$employeeid',
    path: '/employees/$employeeid',
    getParentRoute: () => DashboardOrgslugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register-organization': typeof RegisterOrganizationRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/auth/employee': typeof AuthEmployeeRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/$orgslug': typeof DashboardOrgslugRouteWithChildren
  '/auth/forgot-password/recovery': typeof AuthForgotPasswordRecoveryRoute
  '/dashboard/$orgslug/clients': typeof DashboardOrgslugClientsRoute
  '/dashboard/$orgslug/products': typeof DashboardOrgslugProductsRoute
  '/auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/dashboard/$orgslug/': typeof DashboardOrgslugIndexRoute
  '/dashboard/$orgslug/employees/$employeeid': typeof DashboardOrgslugEmployeesEmployeeidRoute
  '/dashboard/$orgslug/teams/$teamid': typeof DashboardOrgslugTeamsTeamidRoute
  '/dashboard/$orgslug/employees/': typeof DashboardOrgslugEmployeesIndexRoute
  '/dashboard/$orgslug/teams/': typeof DashboardOrgslugTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register-organization': typeof RegisterOrganizationRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/auth/employee': typeof AuthEmployeeRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/forgot-password/recovery': typeof AuthForgotPasswordRecoveryRoute
  '/dashboard/$orgslug/clients': typeof DashboardOrgslugClientsRoute
  '/dashboard/$orgslug/products': typeof DashboardOrgslugProductsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/dashboard/$orgslug': typeof DashboardOrgslugIndexRoute
  '/dashboard/$orgslug/employees/$employeeid': typeof DashboardOrgslugEmployeesEmployeeidRoute
  '/dashboard/$orgslug/teams/$teamid': typeof DashboardOrgslugTeamsTeamidRoute
  '/dashboard/$orgslug/employees': typeof DashboardOrgslugEmployeesIndexRoute
  '/dashboard/$orgslug/teams': typeof DashboardOrgslugTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/register-organization': typeof RegisterOrganizationRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/auth/employee': typeof AuthEmployeeRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/$orgslug': typeof DashboardOrgslugRouteWithChildren
  '/auth/forgot-password/recovery': typeof AuthForgotPasswordRecoveryRoute
  '/dashboard/$orgslug/clients': typeof DashboardOrgslugClientsRoute
  '/dashboard/$orgslug/products': typeof DashboardOrgslugProductsRoute
  '/auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/dashboard/$orgslug/': typeof DashboardOrgslugIndexRoute
  '/dashboard/$orgslug/employees/$employeeid': typeof DashboardOrgslugEmployeesEmployeeidRoute
  '/dashboard/$orgslug/teams/$teamid': typeof DashboardOrgslugTeamsTeamidRoute
  '/dashboard/$orgslug/employees/': typeof DashboardOrgslugEmployeesIndexRoute
  '/dashboard/$orgslug/teams/': typeof DashboardOrgslugTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register-organization'
    | '/select-organization'
    | '/auth/employee'
    | '/auth/register'
    | '/dashboard/$orgslug'
    | '/auth/forgot-password/recovery'
    | '/dashboard/$orgslug/clients'
    | '/dashboard/$orgslug/products'
    | '/auth/forgot-password/'
    | '/dashboard/$orgslug/'
    | '/dashboard/$orgslug/employees/$employeeid'
    | '/dashboard/$orgslug/teams/$teamid'
    | '/dashboard/$orgslug/employees/'
    | '/dashboard/$orgslug/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register-organization'
    | '/select-organization'
    | '/auth/employee'
    | '/auth/register'
    | '/auth/forgot-password/recovery'
    | '/dashboard/$orgslug/clients'
    | '/dashboard/$orgslug/products'
    | '/auth/forgot-password'
    | '/dashboard/$orgslug'
    | '/dashboard/$orgslug/employees/$employeeid'
    | '/dashboard/$orgslug/teams/$teamid'
    | '/dashboard/$orgslug/employees'
    | '/dashboard/$orgslug/teams'
  id:
    | '__root__'
    | '/'
    | '/register-organization'
    | '/select-organization'
    | '/auth/employee'
    | '/auth/register'
    | '/dashboard/$orgslug'
    | '/auth/forgot-password/recovery'
    | '/dashboard/$orgslug/clients'
    | '/dashboard/$orgslug/products'
    | '/auth/forgot-password/'
    | '/dashboard/$orgslug/'
    | '/dashboard/$orgslug/employees/$employeeid'
    | '/dashboard/$orgslug/teams/$teamid'
    | '/dashboard/$orgslug/employees/'
    | '/dashboard/$orgslug/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterOrganizationRoute: typeof RegisterOrganizationRoute
  SelectOrganizationRoute: typeof SelectOrganizationRoute
  AuthEmployeeRoute: typeof AuthEmployeeRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  DashboardOrgslugRoute: typeof DashboardOrgslugRouteWithChildren
  AuthForgotPasswordRecoveryRoute: typeof AuthForgotPasswordRecoveryRoute
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-organization': {
      id: '/select-organization'
      path: '/select-organization'
      fullPath: '/select-organization'
      preLoaderRoute: typeof SelectOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-organization': {
      id: '/register-organization'
      path: '/register-organization'
      fullPath: '/register-organization'
      preLoaderRoute: typeof RegisterOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$orgslug': {
      id: '/dashboard/$orgslug'
      path: '/dashboard/$orgslug'
      fullPath: '/dashboard/$orgslug'
      preLoaderRoute: typeof DashboardOrgslugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/employee': {
      id: '/auth/employee'
      path: '/auth/employee'
      fullPath: '/auth/employee'
      preLoaderRoute: typeof AuthEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$orgslug/': {
      id: '/dashboard/$orgslug/'
      path: '/'
      fullPath: '/dashboard/$orgslug/'
      preLoaderRoute: typeof DashboardOrgslugIndexRouteImport
      parentRoute: typeof DashboardOrgslugRoute
    }
    '/auth/forgot-password/': {
      id: '/auth/forgot-password/'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password/'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$orgslug/products': {
      id: '/dashboard/$orgslug/products'
      path: '/products'
      fullPath: '/dashboard/$orgslug/products'
      preLoaderRoute: typeof DashboardOrgslugProductsRouteImport
      parentRoute: typeof DashboardOrgslugRoute
    }
    '/dashboard/$orgslug/clients': {
      id: '/dashboard/$orgslug/clients'
      path: '/clients'
      fullPath: '/dashboard/$orgslug/clients'
      preLoaderRoute: typeof DashboardOrgslugClientsRouteImport
      parentRoute: typeof DashboardOrgslugRoute
    }
    '/auth/forgot-password/recovery': {
      id: '/auth/forgot-password/recovery'
      path: '/auth/forgot-password/recovery'
      fullPath: '/auth/forgot-password/recovery'
      preLoaderRoute: typeof AuthForgotPasswordRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$orgslug/teams/': {
      id: '/dashboard/$orgslug/teams/'
      path: '/teams'
      fullPath: '/dashboard/$orgslug/teams/'
      preLoaderRoute: typeof DashboardOrgslugTeamsIndexRouteImport
      parentRoute: typeof DashboardOrgslugRoute
    }
    '/dashboard/$orgslug/employees/': {
      id: '/dashboard/$orgslug/employees/'
      path: '/employees'
      fullPath: '/dashboard/$orgslug/employees/'
      preLoaderRoute: typeof DashboardOrgslugEmployeesIndexRouteImport
      parentRoute: typeof DashboardOrgslugRoute
    }
    '/dashboard/$orgslug/teams/$teamid': {
      id: '/dashboard/$orgslug/teams/$teamid'
      path: '/teams/$teamid'
      fullPath: '/dashboard/$orgslug/teams/$teamid'
      preLoaderRoute: typeof DashboardOrgslugTeamsTeamidRouteImport
      parentRoute: typeof DashboardOrgslugRoute
    }
    '/dashboard/$orgslug/employees/$employeeid': {
      id: '/dashboard/$orgslug/employees/$employeeid'
      path: '/employees/$employeeid'
      fullPath: '/dashboard/$orgslug/employees/$employeeid'
      preLoaderRoute: typeof DashboardOrgslugEmployeesEmployeeidRouteImport
      parentRoute: typeof DashboardOrgslugRoute
    }
  }
}

interface DashboardOrgslugRouteChildren {
  DashboardOrgslugClientsRoute: typeof DashboardOrgslugClientsRoute
  DashboardOrgslugProductsRoute: typeof DashboardOrgslugProductsRoute
  DashboardOrgslugIndexRoute: typeof DashboardOrgslugIndexRoute
  DashboardOrgslugEmployeesEmployeeidRoute: typeof DashboardOrgslugEmployeesEmployeeidRoute
  DashboardOrgslugTeamsTeamidRoute: typeof DashboardOrgslugTeamsTeamidRoute
  DashboardOrgslugEmployeesIndexRoute: typeof DashboardOrgslugEmployeesIndexRoute
  DashboardOrgslugTeamsIndexRoute: typeof DashboardOrgslugTeamsIndexRoute
}

const DashboardOrgslugRouteChildren: DashboardOrgslugRouteChildren = {
  DashboardOrgslugClientsRoute: DashboardOrgslugClientsRoute,
  DashboardOrgslugProductsRoute: DashboardOrgslugProductsRoute,
  DashboardOrgslugIndexRoute: DashboardOrgslugIndexRoute,
  DashboardOrgslugEmployeesEmployeeidRoute:
    DashboardOrgslugEmployeesEmployeeidRoute,
  DashboardOrgslugTeamsTeamidRoute: DashboardOrgslugTeamsTeamidRoute,
  DashboardOrgslugEmployeesIndexRoute: DashboardOrgslugEmployeesIndexRoute,
  DashboardOrgslugTeamsIndexRoute: DashboardOrgslugTeamsIndexRoute,
}

const DashboardOrgslugRouteWithChildren =
  DashboardOrgslugRoute._addFileChildren(DashboardOrgslugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterOrganizationRoute: RegisterOrganizationRoute,
  SelectOrganizationRoute: SelectOrganizationRoute,
  AuthEmployeeRoute: AuthEmployeeRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  DashboardOrgslugRoute: DashboardOrgslugRouteWithChildren,
  AuthForgotPasswordRecoveryRoute: AuthForgotPasswordRecoveryRoute,
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
