export interface Colors {
  primary: string;
  surfaceTint: string;
  onPrimary: string;
  primaryContainer: string;
  onPrimaryContainer: string;
  secondary: string;
  onSecondary: string;
  secondaryContainer: string;
  onSecondaryContainer: string;
  tertiary: string;
  onTertiary: string;
  tertiaryContainer: string;
  onTertiaryContainer: string;
  error: string;
  onError: string;
  errorContainer: string;
  onErrorContainer: string;
  background: string;
  onBackground: string;
  surface: string;
  onSurface: string;
  surfaceVariant: string;
  onSurfaceVariant: string;
  outline: string;
  outlineVariant: string;
  shadow: string;
  scrim: string;
  inverseSurface: string;
  inverseOnSurface: string;
  inversePrimary: string;
  primaryFixed: string;
  onPrimaryFixed: string;
  primaryFixedDim: string;
  onPrimaryFixedVariant: string;
  secondaryFixed: string;
  onSecondaryFixed: string;
  secondaryFixedDim: string;
  onSecondaryFixedVariant: string;
  tertiaryFixed: string;
  onTertiaryFixed: string;
  tertiaryFixedDim: string;
  onTertiaryFixedVariant: string;
  surfaceDim: string;
  surfaceBright: string;
  surfaceContainerLowest: string;
  surfaceContainerLow: string;
  surfaceContainer: string;
  surfaceContainerHigh: string;
  surfaceContainerHighest: string;
}

export type Theme = "light" | "dark";

export const APP_COLORS: Record<Theme, Colors> = {
  light: {
    primary: "#2E2E2E",
    surfaceTint: "#2E2E2E",
    onPrimary: "#E6E4D7",
    primaryContainer: "#E3DDCF",
    onPrimaryContainer: "#1E1E1E",
    secondary: "#5E5A52",
    onSecondary: "#F4EFE4",
    secondaryContainer: "#D8D2C4",
    onSecondaryContainer: "#2E2E2E",
    tertiary: "#F26A4B",
    onTertiary: "#FFFFFF",
    tertiaryContainer: "#FFD2BE",
    onTertiaryContainer: "#52170B",
    error: "#DC2626",
    onError: "#FFFFFF",
    errorContainer: "#FFD9D3",
    onErrorContainer: "#720309",
    background: "#E9E4D8",
    onBackground: "#1E1E1E",
    surface: "#E9E4D8",
    onSurface: "#1E1E1E",
    surfaceVariant: "#CFC8B8",
    onSurfaceVariant: "#5E5A52",
    outline: "#A89F8F",
    outlineVariant: "#D2CBBB",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#1E1E1E",
    inverseOnSurface: "#F4EFE4",
    inversePrimary: "#D1CFC0",
    primaryFixed: "#E3DECF",
    onPrimaryFixed: "#1E1E1E",
    primaryFixedDim: "#C9C4B6",
    onPrimaryFixedVariant: "#2E2E2E",
    secondaryFixed: "#DBD7CD",
    onSecondaryFixed: "#1E1E1E",
    secondaryFixedDim: "#C2BDB2",
    onSecondaryFixedVariant: "#5E5A52",
    tertiaryFixed: "#FFD2BE",
    onTertiaryFixed: "#400E04",
    tertiaryFixedDim: "#FBA587",
    onTertiaryFixedVariant: "#7B2815",
    surfaceDim: "#CFC8B8",
    surfaceBright: "#F4EFE4",
    surfaceContainerLowest: "#F9F5EC",
    surfaceContainerLow: "#F4EFE4",
    surfaceContainer: "#E9E4D8",
    surfaceContainerHigh: "#E3DDCF",
    surfaceContainerHighest: "#D8D2C4",
  },
  dark: {
    primary: "#D1CFC0",
    surfaceTint: "#D1CFC0",
    onPrimary: "#363636",
    primaryContainer: "#363636",
    onPrimaryContainer: "#D1CFC0",
    secondary: "#D9CFC2",
    onSecondary: "#1C1C1C",
    secondaryContainer: "#2A2A2A",
    onSecondaryContainer: "#D1CFC0",
    tertiary: "#F88C6A",
    onTertiary: "#39150D",
    tertiaryContainer: "#7B2815",
    onTertiaryContainer: "#FFD2BE",
    error: "#FF847D",
    onError: "#460105",
    errorContainer: "#861118",
    onErrorContainer: "#FFD8D4",
    background: "#141414",
    onBackground: "#E8E3DA",
    surface: "#141414",
    onSurface: "#E8E3DA",
    surfaceVariant: "#2A2A2A",
    onSurfaceVariant: "#8E8A83",
    outline: "#5C5A56",
    outlineVariant: "#2C2C2C",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#E8E3DA",
    inverseOnSurface: "#141414",
    inversePrimary: "#2E2E2E",
    primaryFixed: "#E3DECF",
    onPrimaryFixed: "#1E1E1E",
    primaryFixedDim: "#C9C4B6",
    onPrimaryFixedVariant: "#2E2E2E",
    secondaryFixed: "#DBD7CD",
    onSecondaryFixed: "#1E1E1E",
    secondaryFixedDim: "#C2BDB2",
    onSecondaryFixedVariant: "#5E5A52",
    tertiaryFixed: "#FFD2BE",
    onTertiaryFixed: "#400E04",
    tertiaryFixedDim: "#FBA587",
    onTertiaryFixedVariant: "#7B2815",
    surfaceDim: "#101010",
    surfaceBright: "#2A2A2A",
    surfaceContainerLowest: "#0B0B0B",
    surfaceContainerLow: "#171717",
    surfaceContainer: "#1C1C1C",
    surfaceContainerHigh: "#222222",
    surfaceContainerHighest: "#2A2A2A",
  },
} as const;
